### ISSUE TITLE
Problem with Transactional Emails

### ISSUE THREAD

**Issue by aurmil** [jreinke/magento-highlighter#4]
When accessing transcational email add/edit form, textareas are not visible

**Comment by maxmino** [comment]
Me too, same problem.
I'm using 1.1.1 version.

**Comment by jreinke** [comment]
Do you have something in console? (Javascript error for example)

**Comment by maxmino** [comment]
No errors in console, I've seen, inspectioning the html code, that text-area had a style attribute  with value of -1000 on position element

**Comment by jreinke** [comment]
Problem is I can't reproduce it...

**Comment by maxmino** [comment]
If you want I can give an access to my dev environment, at this moment I've disabled the highlighter component but I can re-enable it with just one click.

**Comment by jreinke** [comment]
Ok, please contact me through https://www.bubbleshop.net/contacts/

**Comment by aurmil** [comment]
same, no JS errors
div.CodeMirror.cm-s-mbo.CodeMirror-wrap has "display: none" in its style attribute

**Comment by aurmil** [comment]
Now it causes a bug w/ CMS blocks edit page: both blocks (wysiwyg + html content) appear together
